#!/usr/bin/bash
# use: git config core.hooksPath .gitHooks

py=$(which py || which python || which python3)
if [[ -z $py ]]
then 
  echo "No python found"
  exit 0
fi

cd $(git rev-parse --show-toplevel)
sompy=$(pwd)/sompy/somutil

mdjs=
svgs=
txts=

for file in `git diff-index --cached --name-only HEAD`;
do
  if [[ -f $file ]]
  then
    add=1
    if [[ $file == *.mdj ]]; then mdjs="$mdjs $file"
    elif [[ $file == *.svg ]]; then svgs="$svgs $file"
    elif [[ $file == *.py ]] || [[ $file == *.cpp ]] || [[ $file == *.h ]]  || [[ $file == *.cmd ]] 
    then
      txts="$txts $file" 
    else
      add=0
    fi
    
    if [[ $add -eq 1 ]]; then git add $file; fi
  fi
done

if [[ -n $mdjs ]]; then
  echo cleaning mdj files
  $py $sompy/cleanMdj.py $mdjs
fi
if [[ -n $svgs ]]; then
  echo cleaning svg files
  $py $sompy/cleanSvg.py $svgs
fi
if [[ -n $txts ]]; then
  echo cleaning text files
  $py $sompy/cleanTxt.py $txts
fi
