#!/usr/bin/bash
# use: git config core.hooksPath .gitHooks

py=$(which py || which python || which python3)
if [[ -z $py ]]; then exit 0; fi
echo "Using python: $py"

cd $(git rev-parse --show-toplevel)
echo current directory: $(pwd)

for file in `git diff-index --cached --name-only HEAD`;
do
  if [[ -f $file ]]
  then
    add=1
    echo checking file: $file 
    if [[ $file == *.mdj ]]
    then 
      echo cleaning mdj file: $file
      $py sompy/cleanMdj.py $file
    elif [[ $file == *.svg ]]
    then 
      echo cleaning svg file: $file
      $py sompy/cleanSvg.py $file
    elif [[ $file == *.py ]] || [[ $file == *.cpp ]] || [[ $file == *.h ]] 
    then 
      echo cleaning text file: $file
      $py sompy/cleanTxt.py $file
    else
      add=0
    fi
    
    if [[ $add -eq 1 ]]
    then 
      git add $file
    fi
  fi
done
