#!/usr/bin/bash
# use: git config core.hooksPath .gitHooks

py=$(which py || which python || which python3)
if [[ -z $py ]]; then exit 0; fi
echo "Using python: $py"

cd $(git rev-parse --show-toplevel)
echo current directory: $(pwd)

for file in `git diff-index --cached --name-only HEAD`;
do
  if [[ -f $file ]]
  then
    if [ $file == *.mdj ] then $py scripts/cleanMdj.py $file; fi
    if [ $file == *.svg ] then $py scripts/cleanSvg.py $file; fi
  fi
done
