# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=ci
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),ci)
  cppu_test_config = ci

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := cppu_test

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

cppu_test:
ifneq (,$(cppu_test_config))
	@echo "==== Building cppu_test ($(cppu_test_config)) ===="
	@${MAKE} --no-print-directory -C . -f cppu_test.make config=$(cppu_test_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f cppu_test.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  ci"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   cppu_test"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"