# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=ci
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),ci)
  stop_app_config = ci
  run_tests_config = ci

else ifeq ($(config),qnd)
  stop_app_config = qnd
  run_tests_config = qnd

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := stop_app run_tests

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

stop_app:
ifneq (,$(stop_app_config))
	@echo "==== Building stop_app ($(stop_app_config)) ===="
	@${MAKE} --no-print-directory -C . -f stop_app.make config=$(stop_app_config)
endif

run_tests:
ifneq (,$(run_tests_config))
	@echo "==== Building run_tests ($(run_tests_config)) ===="
	@${MAKE} --no-print-directory -C . -f run_tests.make config=$(run_tests_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f stop_app.make clean
	@${MAKE} --no-print-directory -C . -f run_tests.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  ci"
	@echo "  qnd"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   stop_app"
	@echo "   run_tests"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"