# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=ci
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),ci)
  systests_app_config = ci
  systests_tests_config = ci

else ifeq ($(config),qnd)
  systests_app_config = qnd
  systests_tests_config = qnd

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := systests_app systests_tests

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

systests_app:
ifneq (,$(systests_app_config))
	@echo "==== Building systests_app ($(systests_app_config)) ===="
	@${MAKE} --no-print-directory -C . -f systests_app.make config=$(systests_app_config)
endif

systests_tests:
ifneq (,$(systests_tests_config))
	@echo "==== Building systests_tests ($(systests_tests_config)) ===="
	@${MAKE} --no-print-directory -C . -f systests_tests.make config=$(systests_tests_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f systests_app.make clean
	@${MAKE} --no-print-directory -C . -f systests_tests.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  ci"
	@echo "  qnd"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   systests_app"
	@echo "   systests_tests"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"