# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=ci
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),ci)
  systemtests_stop_config = ci
  systemtests_run_config = ci

else ifeq ($(config),qnd)
  systemtests_stop_config = qnd
  systemtests_run_config = qnd

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := systemtests_stop systemtests_run

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

systemtests_stop:
ifneq (,$(systemtests_stop_config))
	@echo "==== Building systemtests_stop ($(systemtests_stop_config)) ===="
	@${MAKE} --no-print-directory -C . -f systemtests_stop.make config=$(systemtests_stop_config)
endif

systemtests_run:
ifneq (,$(systemtests_run_config))
	@echo "==== Building systemtests_run ($(systemtests_run_config)) ===="
	@${MAKE} --no-print-directory -C . -f systemtests_run.make config=$(systemtests_run_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f systemtests_stop.make clean
	@${MAKE} --no-print-directory -C . -f systemtests_run.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  ci"
	@echo "  qnd"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   systemtests_stop"
	@echo "   systemtests_run"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"