name: C/C++ CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: "build CppuTest"
      run: cd BuildCppUTest; ls
    - name: "build tests"
      run: cd make; ls
    # run: cd make; make -f tests.make
    # - name: run
    #   run: make/bin/tests
