#   ============================================================
#   continuous integration setup 
#   ============================================================
#   created by Manfred Sorgo
name: C/C++ CI

on:
  push:
    branches: [ "dev_98", "dev_20", "release" ]
  pull_request:
    branches: [ "dev_98", "dev_20", "release" ]

jobs:
  buildAndRunAll:

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v3
      with:
         submodules: 'true'

    - name: build and run all
      run: chmod 755 make/*.sh; make/build.sh -cx

    - name: check coverage
      run: make/runGcov.sh

    # - name: check env
    #   run: chmod 755 make/checkEnv.sh; make/checkEnv.sh

